/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package moveonscreen;

import java.awt.event.KeyEvent;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author HbTO
 */
public class Screen extends javax.swing.JFrame {
    
    
    //Un socket es la combinacion de una dir ip con un puerto.
    private Socket socket;
    
    
    /*Canales de comunicacion "espacio de memoria entre usuario/servidor.
      canal entrada, canal salida
      bits*/
    private InputStream inputStream;
    private OutputStream outputStream;
    
    //variables primitivas de java
    private DataInputStream entradaDatos;
    private DataOutputStream salidaDatos;
    
    
    /**
     * Creates new form Screen
     */
    public Screen() {
        initComponents();
        setLocationRelativeTo(null);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        lblImage = new javax.swing.JLabel();
        btnArriba = new javax.swing.JButton();
        btnAbajo = new javax.swing.JButton();
        btnDer = new javax.swing.JButton();
        btnIzq = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuBotones = new javax.swing.JMenu();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MoveOnScreen");
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/goku_image.png"))); // NOI18N

        btnArriba.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/up.png"))); // NOI18N
        btnArriba.setEnabled(false);
        btnArriba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArribaActionPerformed(evt);
            }
        });

        btnAbajo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/down.png"))); // NOI18N
        btnAbajo.setEnabled(false);
        btnAbajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbajoActionPerformed(evt);
            }
        });

        btnDer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/right.png"))); // NOI18N
        btnDer.setEnabled(false);
        btnDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerActionPerformed(evt);
            }
        });

        btnIzq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/left.png"))); // NOI18N
        btnIzq.setEnabled(false);
        btnIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzqActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        menuBotones.setText("Botones");
        menuBotones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                menuBotonesMousePressed(evt);
            }
        });
        jMenuBar1.add(menuBotones);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btnIzq)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnArriba)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAbajo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnDer))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblImage)))
                .addContainerGap(217, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(lblImage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnIzq)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnArriba)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbajo))
                    .addComponent(btnDer))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
     public void conexion(int puerto, String host){
        /* host=ip puerto=puerto al que se conectara  */
        try {
            socket = new Socket(host, puerto);
            String dato = "setplayer|300|300|goku_image.png";
            enviaDatos(dato);
            
        } catch (IOException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    public void recibeDatos(){
        
        try {
            inputStream = socket.getInputStream();
            entradaDatos = new DataInputStream(inputStream);
            //System.out.println("RECIBEDATOS INTERFACE"+entradaDatos.readUTF());
            
            //agregarMsg(entradaDatos.readUTF());
        } catch (IOException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    
    public void enviaDatos(String datos){
        
        try {
            outputStream = socket.getOutputStream();
            salidaDatos = new DataOutputStream(outputStream);
            
            salidaDatos.writeUTF(datos);
            salidaDatos.flush();
             System.out.println("Se envio esto: "+datos);
            
        } catch (IOException ex) {
            Logger.getLogger(Screen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
    
    
    
    
    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        char tecla = evt.getKeyChar();
        /*System.out.println("es esto: "+KeyEvent.VK_UP);
        System.out.println("da esto: "+evt.getKeyCode());*/
        String comando="move|";
        String ejecutar;
        
        //MOVER HACIA ARRIBA
        if(KeyEvent.VK_UP == evt.getKeyCode()){
          int x =lblImage.getX();
          int y =lblImage.getY();
          
          lblImage.setLocation(x, y-5);
         
          System.out.println("Move to Up");
          ejecutar="up";
          enviaDatos(comando+ejecutar);enviaDatos(comando+ejecutar);enviaDatos(comando+ejecutar);
          
          
          //lblImage.repaint();
        }
        
         //MOVER HACIA ABAJO
        if(KeyEvent.VK_DOWN == evt.getKeyCode()){
          int x =lblImage.getX();
          int y =lblImage.getY();
          
          lblImage.setLocation(x, y+5);
         
          System.out.println("Move to Down");
          //lblImage.repaint();
          ejecutar="down";
          enviaDatos(comando+ejecutar);enviaDatos(comando+ejecutar);enviaDatos(comando+ejecutar);
          
        }
        
        //MOVER HACIA IZQUIERDA
        if(KeyEvent.VK_LEFT == evt.getKeyCode()){
          int x =lblImage.getX();
          int y =lblImage.getY();
          
          lblImage.setLocation(x-5, y);
         
          System.out.println("Move to Left");
          //lblImage.repaint();
          ejecutar="left";
          enviaDatos(comando+ejecutar);enviaDatos(comando+ejecutar);enviaDatos(comando+ejecutar);
          
        }
        
        //MOVER HACIA DERECHA
        if(KeyEvent.VK_RIGHT == evt.getKeyCode()){
          int x =lblImage.getX();
          int y =lblImage.getY();
          
          lblImage.setLocation(x+5, y);
         
          System.out.println("Move to Right");
          //lblImage.repaint();
          ejecutar="right";
          enviaDatos(comando+ejecutar);enviaDatos(comando+ejecutar);enviaDatos(comando+ejecutar);
          
        }
        
        
        
    }//GEN-LAST:event_formKeyPressed

    private void btnArribaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArribaActionPerformed
        int x =lblImage.getX();
          int y =lblImage.getY();
          
          lblImage.setLocation(x, y-5);
          
          
          String comando="move|";
          String ejecutar;
          ejecutar="up";
          enviaDatos(comando+ejecutar);
    }//GEN-LAST:event_btnArribaActionPerformed

    private void btnAbajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbajoActionPerformed
        int x =lblImage.getX();
          int y =lblImage.getY();
          
          lblImage.setLocation(x, y+5);
          
          String comando="move|";
          String ejecutar;
          ejecutar="down";
          enviaDatos(comando+ejecutar);
    }//GEN-LAST:event_btnAbajoActionPerformed

    private void btnDerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerActionPerformed
        int x =lblImage.getX();
          int y =lblImage.getY();
          
          lblImage.setLocation(x+5, y);
          
          String comando="move|";
          String ejecutar;
          ejecutar="right";
          enviaDatos(comando+ejecutar);
    }//GEN-LAST:event_btnDerActionPerformed

    private void btnIzqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzqActionPerformed
        int x =lblImage.getX();
          int y =lblImage.getY();
          
          lblImage.setLocation(x-5, y);
          
          String comando="move|";
          String ejecutar;
          ejecutar="left";
          enviaDatos(comando+ejecutar);enviaDatos(comando+ejecutar);enviaDatos(comando+ejecutar);
    }//GEN-LAST:event_btnIzqActionPerformed

    private void menuBotonesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuBotonesMousePressed
       System.out.println("ESTO :"+btnArriba.isEnabled());
        
        if(btnArriba.isEnabled()){
            btnArriba.setEnabled(false);
            btnAbajo.setEnabled(false);
            btnIzq.setEnabled(false);
            btnDer.setEnabled(false);
            
            
            Screen.this.requestFocus(true);
           
       }else{
          btnArriba.setEnabled(true);
          btnAbajo.setEnabled(true);
          btnIzq.setEnabled(true);
          btnDer.setEnabled(true); 

       }
    }//GEN-LAST:event_menuBotonesMousePressed

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        Screen.this.requestFocus(true);
    }//GEN-LAST:event_formMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Screen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Screen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbajo;
    private javax.swing.JButton btnArriba;
    private javax.swing.JButton btnDer;
    private javax.swing.JButton btnIzq;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblImage;
    private javax.swing.JMenu menuBotones;
    // End of variables declaration//GEN-END:variables
}
